PREFIX_TO_TRAFFIC_ID = {
    # Chat
    'aim_chat_3a': 0,
    'aim_chat_3b': 0,
    'aimchat1': 0,
    'aimchat2': 0,
    'facebook_chat_4a': 0,
    'facebook_chat_4b': 0,
    'facebookchat1': 0,
    'facebookchat2': 0,
    'facebookchat3': 0,
    'gmailchat1': 0,
    'gmailchat2': 0,
    'gmailchat3': 0,
    'hangout_chat_4b': 0,
    'hangouts_chat_4a': 0,
    'icq_chat_3a': 0,
    'icq_chat_3b': 0,
    'icqchat1': 0,
    'icqchat2': 0,
    'skype_chat1a': 0,
    'skype_chat1b': 0,
    # Email
    'email1a': 1,
    'email1b': 1,
    'email2a': 1,
    'email2b': 1,
    # File Transfer
    'ftps_down_1a': 2,
    'ftps_down_1b': 2,
    'ftps_up_2a': 2,
    'ftps_up_2b': 2,
    'sftp1': 2,
    'sftp_down_3a': 2,
    'sftp_down_3b': 2,
    'sftp_up_2a': 2,
    'sftp_up_2b': 2,
    'sftpdown1': 2,
    'sftpdown2': 2,
    'sftpup1': 2,
    'scpup1': 2,
    'scpup2': 2,
    'scpup3': 2,
    'scpup5': 2,
    'scpup6': 2,
    'scp1': 2,
    'scpdown1': 2,
    'scpdown2': 2,
    'scpdown3': 2,
    'scpdown4': 2,
    'scpdown5': 2,
    'scpdown6': 2,
    'skype_file1': 2,
    'skype_file2': 2,
    'skype_file3': 2,
    'skype_file4': 2,
    'skype_file5': 2,
    'skype_file6': 2,
    'skype_file7': 2,
    'skype_file8': 2,
    # Streaming
    'vimeo1': 3,
    'vimeo2': 3,
    'vimeo3': 3,
    'vimeo4': 3,
    'spotify1': 3,
    'spotify2': 3,
    'spotify3': 3,
    'spotify4': 3,
    'netflix1': 3,
    'netflix2': 3,
    'netflix3': 3,
    'netflix4': 3,
    'youtube1': 3,
    'youtube2': 3,
    'youtube3': 3,
    'youtube4': 3,
    'youtube5': 3,
    'youtube6': 3,
    'youtubehtml5_1': 3,
    'facebook_video1a': 3,
    'facebook_video1b': 3,
    'facebook_video2a': 3,
    'facebook_video2b': 3,
    'hangouts_video1b': 3,
    'hangouts_video2a': 3,
    'hangouts_video2b': 3,
    'skype_video1a': 3,
    'skype_video1b': 3,
    'skype_video2a': 3,
    'skype_video2b': 3,
    # VOIP
    'voipbuster1b': 4,
    'voipbuster2b': 4,
    'voipbuster3b': 4,
    'voipbuster_4a': 4,
    'voipbuster_4b': 4,
    'facebook_audio1a': 4,
    'facebook_audio1b': 4,
    'facebook_audio2a': 4,
    'facebook_audio2b': 4,
    'facebook_audio3': 4,
    'facebook_audio4': 4,
    'hangouts_audio1a': 4,
    'hangouts_audio1b': 4,
    'hangouts_audio2a': 4,
    'hangouts_audio2b': 4,
    'hangouts_audio3': 4,
    'hangouts_audio4': 4,
    'skype_audio1a': 4,
    'skype_audio1b': 4,
    'skype_audio2a': 4,
    'skype_audio2b': 4,
    'skype_audio3': 4,
    'skype_audio4': 4,
    # VPN: Chat
    'vpn_aim_chat1a': 5,
    'vpn_aim_chat1b': 5,
    'vpn_facebook_chat1a': 5,
    'vpn_facebook_chat1b': 5,
    'vpn_hangouts_chat1a': 5,
    'vpn_hangouts_chat1b': 5,
    'vpn_icq_chat1a': 5,
    'vpn_icq_chat1b': 5,
    'vpn_skype_chat1a': 5,
    'vpn_skype_chat1b': 5,
    # VPN: File Transfer
    'vpn_ftps_a': 6,
    'vpn_ftps_b': 6,
    'vpn_sftp_a': 6,
    'vpn_sftp_b': 6,
    'vpn_skype_files1a': 6,
    'vpn_skype_files1b': 6,
    # VPN: Email
    'vpn_email2a': 7,
    'vpn_email2b': 7,
    # VPN: Streaming
    'vpn_vimeo_a': 8,
    'vpn_vimeo_b': 8,
    'vpn_youtube_a': 8,
    'vpn_netflix_a': 8,
    'vpn_spotify_a': 8,
    # VPN VoIP
    'vpn_facebook_audio2': 9,
    'vpn_hangouts_audio1': 9,
    'vpn_hangouts_audio2': 9,
    'vpn_skype_audio1': 9,
    'vpn_skype_audio2': 9,
    'vpn_voipbuster1a': 9,
    'vpn_voipbuster1b': 9,
}

ID_TO_TRAFFIC = {
    0: 'Chat',
    1: 'Email',
    2: 'File Transfer',
    3: 'Streaming',
    4: 'Voip',
    5: 'VPN: Chat',
    6: 'VPN: File Transfer',
    7: 'VPN: Email',
    8: 'VPN: Streaming',
    9: 'VPN: Voip',
}